<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../BuildingBlocks/Outclass.BuildingBlocks.Infrastructure/Outclass.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="../Outclass.FileStorage.Application/Outclass.FileStorage.Application.csproj" />
    <ProjectReference Include="../Outclass.FileStorage.Domain/Outclass.FileStorage.Domain.csproj" />
  </ItemGroup>
</Project>
